const fs = require("fs")
const path = require("path")

// Read package.json
const packagePath = path.join(__dirname, "..", "package.json")
const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"))

// Generate version.ts
const versionContent = `/**
 * Auto-generated file - do not edit manually
 * This file is generated by scripts/generate-version.js
 */

export const LIBRARY_NAME = "${packageJson.name}"
export const LIBRARY_VERSION = "${packageJson.version}"
export const LIBRARY_ORIGIN = "${packageJson.name}@${packageJson.version}"
`

// Write to src/version.ts
const versionPath = path.join(__dirname, "..", "src", "version.ts")
fs.writeFileSync(versionPath, versionContent, "utf8")

console.log(`Generated version.ts: ${packageJson.name}@${packageJson.version}`)
